# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "MattHodge/Windows2012R2Core-WMF5-NOCM"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
    vb.linked_clone = true
  end

  config.vm.provider "hyperv" do |hv|
    # hyperv provisioner doesn't name things nicey
    randy = rand(10000)
    hv.vmname = "Windows2012R2Core-WMF5-NOCM" + randy.to_s
    hv.cpus = 1
    hv.memory = 1024
    hv.differencing_disk = true
  end

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
end
