# -*- mode: ruby -*-
# vi: set ft=ruby :

# set a default provider
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.box = "MattHodge/Windows2012R2Core-WMF5-NOCM"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
  end
end
