# -*- mode: ruby -*-
# vi: set ft=ruby :

# set a default provider
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  config.vm.box = "MattHodge/Windows2016-WMF5-NOCM"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
  end

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
  end

  config.vm.provision "shell", path: "install_octopus.ps1"

  config.vm.network "forwarded_port", guest: 80, host: 8080
end
