# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "MattHodge/Windows2016-WMF5-NOCM"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "2048"
    vb.linked_clone = true
  end

  config.vm.provider "hyperv" do |hv|
    # hyperv provisioner doesn't name things nicey
    randy = rand(10000)
    hv.vmname = "OctopusDeploy" + randy.to_s
    hv.cpus = 1
    hv.memory = 2048
    hv.differencing_disk = true
  end

  config.vm.provision "shell", path: "install_octopus.ps1"

  config.vm.network "forwarded_port", guest: 80, host: 8081
end
